# Sterngth S4 Remake Config
on load:
	# Maximum Strength
	set {-strength.max} to 5
	# Minimum Strength
	set {-strength.min} to -3
	# Default Strength (On First Join)
	set {-strength.default} to 0
	# Enable/Disable Strength pots
	set {-strength.pots} to false
	# Axe Weapon Stun Duration (In Seconds)
	set {-axe.stun} to 1 # In Seconds <------
	# Enable / Disable Mace
	set {-mace.allow} to true 
	# Mace Cooldown
	set {-mace.cooldown} to 30 # In Seconds <-----
